stages:
  - build_and_push
variables:
  DOCKER_CERT_PATH: /certs/client
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: /certs
  DOCKER_TLS_VERIFY: 1
build_image:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
  tags:
    - self-hosted
  stage: build_and_push
  services:
    - docker:dind
  before_script:
    - until docker info; do sleep 1; done
    - cd $CI_PROJECT_DIR
  script:
    - docker run --rm --privileged tonistiigi/binfmt --install all
    - docker context create tls-env
    - docker buildx create --name mybuilder --use tls-env
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker buildx build --provenance=false --platform linux/amd64,linux/arm64 --tag $CI_REGISTRY_IMAGE:alpha0.1.0 --push .
