apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dpsv-pvc
  namespace: dpsv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard