on:
  push:
    branches: ["main","master","CI"]
jobs:
  main:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: qemu setup
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: buildx setup
        uses: docker/setup-buildx-action@v3

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build
        uses: docker/build-push-action@v5
        with:
          options: "--network=host"
          context: .
          push: true
          tags: ${{ secrets.IMAGE_NAME }}:alpha0.1.0
          platforms: linux/amd64,linux/arm64
